
 
   
  CREATE TABLE "JOP"."GENDER" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	 CONSTRAINT "GENDER_PK" PRIMARY KEY ("ID")
  
   ) ;
   
   CREATE TABLE "JOP"."JOBS" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE), 
	"SALARY" NUMBER(9,2), 
	 CONSTRAINT "JOBS_PK" PRIMARY KEY ("ID"));

 CREATE TABLE "JOP"."EMPLOYEES" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"GENDER_ID" NUMBER(38,0), 
	"JOB_ID" NUMBER(38,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"BIRTHDATE" DATE, 
	"SALARY" FLOAT(53), 
	 CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "FK_GENDER" FOREIGN KEY ("GENDER_ID")
	  REFERENCES "JOP"."GENDER" ("ID") ENABLE, 
	 CONSTRAINT "FK_JOBS" FOREIGN KEY ("JOB_ID")
	  REFERENCES "JOP"."JOBS" ("ID") ENABLE
   ) ;
   

  CREATE TABLE "JOP"."EMPLOYEE_WORKED_HOURS" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"EMPLOYEE_ID" NUMBER(38,0), 
	"WORKED_HOURS" NUMBER(38,0), 
	"WORKED_DATE" DATE, 
	 CONSTRAINT "EMPLOYEE_WORKED_HOURS_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "FK_EMPLOYEES" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "JOP"."EMPLOYEES" ("ID") ENABLE
   ) ;
  
  
